<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="zz-PC" ignored="2" name="LoginTest" tests="2" failures="1" timestamp="06 三月 2018 06:41:52 GMT" time="22.901" errors="0">
  <testcase name="normal" time="20.52" classname="liyan.dangjian.testsuit.SelectDetailByUserId"/>
  <testcase name="nullYear" time="0.069" classname="liyan.dangjian.testsuit.SelectDetailByUserId">
    <failure type="java.lang.AssertionError" message="expected [401] but found [&amp;quot;rest.success&amp;quot;]">
      <![CDATA[java.lang.AssertionError: expected [401] but found ["rest.success"]
at liyan.dangjian.testsuit.SelectDetailByUserId.nullYear(SelectDetailByUserId.java:51)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- nullYear -->
  <testcase name="nullOrgId" time="0.0" classname="liyan.dangjian.testsuit.SelectDetailByUserId">
    <ignored/>
  </testcase> <!-- nullOrgId -->
  <testcase name="nullToken" time="0.0" classname="liyan.dangjian.testsuit.SelectDetailByUserId">
    <ignored/>
  </testcase> <!-- nullToken -->
</testsuite> <!-- LoginTest -->
